Cg/payload
Prodooh/prodooh-front pull request #3
Opened 2023-04-19 23:17 UTC by cristoferprodooh

2023-04-19 23:30 UTC, Prodooh commented on src/app/layouts/rightsidebar/rightsidebar.component.ts
> +    this.payload = this.localStorageService.get('payload');
Esta de mas

2023-04-24 18:42 UTC, Prodooh requested changes

2023-04-24 18:42 UTC, Prodooh commented on src/app/core/services/preference.service.ts
> +  savePreferences(type: string, value: string | boolean) {
El backend quedo que actualiza todo el payload

2023-04-24 18:42 UTC, Prodooh commented on src/app/layouts/horizontal/horizontal.component.ts
> +    this.subscriptions.add(this.eventService.subscribe('changeTopbar', (topbar) => {
Hay que cambiar las identaciones cuando se agrega en un add 
this.subscriptions.add(
      this.eventService.subscribe('changeTopbar', (topbar) => {
           this.topbar = topbar;
           this.changeTopbar(this.topbar);
      })
);

2023-04-24 18:42 UTC, Prodooh commented on src/app/layouts/horizontal/horizontal.component.ts
> +    this.subscriptions.add(this.eventService.subscribe('changeTopbar', (topbar) => {
jaja borro mis identaciones

2023-04-24 18:42 UTC, Prodooh commented on src/app/layouts/layout.component.ts
> +    this.subscriptions.add(this.eventService.subscribe('layout', (layout) => {
Hay que identar todos los add

2023-04-24 18:42 UTC, Prodooh commented on src/app/layouts/layout.component.ts
> +  }
Creo que no es tan necesario tener el ondestroy en el layout por que nunca se destruye, hay que revisar con un log si en algun punto llega a destruirse

2023-04-24 18:43 UTC, cristoferprodooh commented on src/app/layouts/rightsidebar/rightsidebar.component.ts
> +    this.payload = this.localStorageService.get('payload');
ya quedo eliminado!

2023-04-24 18:44 UTC, cristoferprodooh commented on src/app/app.component.ts
> +      error(msg) {
listo eliminado

2023-04-24 18:44 UTC, cristoferprodooh commented on src/app/core/services/preference.service.ts
> +  savePreferences(type: string, value: string | boolean) {
ya se hizo el cambio

2023-04-24 18:45 UTC, cristoferprodooh commented on src/app/layouts/horizontal/horizontal.component.ts
> +    this.subscriptions.add(this.eventService.subscribe('changeTopbar', (topbar) => {
vale ya quedo!

2023-04-24 18:49 UTC, cristoferprodooh commented on src/app/layouts/layout.component.ts
> +  }
se queda por que muere al cerrar sesion

2023-04-24 19:16 UTC, merged